server:
    port: 8443
    contextPath: /publisher

multipart:
    maxFileSize: 10MB
    maxRequestSize: 128KB

spring:
    profiles:
        active: prod
        include: ldapgrp

    datasource:
        dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
        url: jdbc:mysql://baobab.giprecia.net:3306/publisher?autoreconnect=true
        databaseName:
        serverName:
        username: publisher
        password: M2PplpuNEWS
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

    jpa:
        database-platform: org.esupportail.publisher.utils.MySQL5InnoDBCompressedDialect
        database: MYSQL
        openInView: false
        show_sql: false
        generate-ddl: false
        hibernate:
            ddl-auto: none
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
            hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

    mail:
        baseUrl: http://localhost:8080

    thymeleaf:
        mode: XHTML
        cache: true

logging:
    config: "classpath:logback.xml"

metrics:
    jmx.enabled: true
    spark:
        enabled: false
        host: localhost
        port: 9999
    graphite:
        enabled: false
        host: localhost
        port: 2003
        prefix: publisher

cache:
    timeToLiveSeconds: 3600
    ehcache:
        maxBytesLocalHeap: 256M

ldap:
    base: dc=esco-centre,dc=fr
    urls: ldap://chene.giprecia.net:389/
    userDn: cn=admin,ou=administrateurs,dc=esco-centre,dc=fr
    password: LplmENT
    timeLimit: 20000
    countLimit: 2000
    otherUserDisplayedAttributes: mail,ESCOUAI
    userGroupAttribute: isMemberOf
    otherUserOtherAttributes: isMemberOf, ENTPersonProfils, ESCOPersonProfils, ENTPersonJointure
    groupDNContainsDisplayName: true
    groupKeyMemberRegex: "cn=(.*),ou=groups,dc=esco-centre,dc=fr"
    groupKeyMemberIndex: 1
    userKeyMemberRegex: "uid=(.*),ou=people,dc=esco-centre,dc=fr"
    userKeyMemberIndex: 1
    groupDisplayNameRegex: ".*:([^:]*)"
    groupResolveUserMember: true
    groupResolveUserMemberByUserAttributes: true
    escoGroupApplicationMatcher: "((esco)|(cfa)|(clg37)|(agri)):Applications:Publication_annonces:[^:]*"
    escoGroupApplicationNameRegex: "[^:]*:([^:]*):([^:]*):[^:]*"
    escoGroupApplicationNameIndex: "1,2"

cas:
    url:
        prefix: https://test.reciacas.fr/cas/
        login: https://test.reciacas.fr/cas/login
        logout: https://test.reciacas.fr/cas/logout

app:
    service:
        security: https://test-lycee.reciaent.fr/publisher/j_spring_cas_security_check
    admin:
        userName: admin
        groupName: "esco:admin:central"

    cors:
        allowed:
            origins: "*"
    upload:
            path: "/home/esco/uploads/"
